/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in real apps and is committed here so the
// example can typecheck as a standalone template.
